name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Или используйте другую подходящую версию
      - name: Setup project
        run: make setup
      - name: Run tests
        run: make test
      - name: Run lint
        run: make lint
